# -*- coding: utf-8 -*-
"""
/***************************************************************************
 expreseau_gtfs_qgis
                                 A QGIS plugin
 Application librairie expreseau_gtfs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-11
        copyright            : (C) 2024 by Lucas FAGES
        email                : lucas.fages@cnrs.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load expreseau_gtfs_qgis class from file expreseau_gtfs_qgis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ExpreseauGTFS import expreseau_gtfs_qgis
    return expreseau_gtfs_qgis(iface)
